import { useEffect, useRef, useState } from 'react';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import type { DiagnosisSketch, SketchPoint, SketchSegment } from '../types';
import { addressLabel, formatLength, geometryLength, midpoint, nextSegmentName, reverseGeocode, searchAddress, withTotals } from '../lib/diagnosisSketch';
import { uid } from '../lib/helpers';

type Props={value:DiagnosisSketch;onChange:(v:DiagnosisSketch)=>void};
type Mode='idle'|'draw'|'branch'|'edit';
const center:L.LatLngExpression=[-23.55,-46.31];
export function DiagnosisSketchMap({value,onChange}:Props){
 const el=useRef<HTMLDivElement|null>(null),map=useRef<L.Map|null>(null),layer=useRef<L.LayerGroup|null>(null),draftLayer=useRef<L.Polyline|null>(null),history=useRef<DiagnosisSketch[]>([]);
 const [mode,setMode]=useState<Mode>('idle'),[draft,setDraft]=useState<{lat:number;lng:number}[]>([]),[branchPoint,setBranchPoint]=useState<SketchPoint|null>(null),[message,setMessage]=useState(''),[query,setQuery]=useState(''),[searching,setSearching]=useState(false);
 const current=useRef(value);current.current=value;
 const commit=(next:DiagnosisSketch)=>{history.current.push(current.current);if(history.current.length>20)history.current.shift();onChange(withTotals(next));};
 const undo=()=>{const prev=history.current.pop();if(prev)onChange(prev)};
 const startNew=()=>{setMode('draw');setBranchPoint(null);setDraft([]);setMessage('Toque no mapa para adicionar os pontos do novo trecho.');};
 const startBranch=()=>{setMode('branch');setDraft([]);setBranchPoint(null);setMessage('Toque em um ponto existente para iniciar o novo ramal.');};
 const fitWork=()=>{const m=map.current;if(!m||!value.segments.length)return;const b=L.latLngBounds(value.segments.flatMap(x=>x.coordinates.map(p=>[p.lat,p.lng] as [number,number])));m.fitBounds(b,{padding:[18,18],maxZoom:19});};
 const doSearch=async()=>{const q=query.trim();if(!q)return;setSearching(true);setMessage('Buscando endereço...');const found=await searchAddress(q);setSearching(false);if(!found){setMessage('Endereço não localizado. Tente incluir município e UF.');return}map.current?.setView([found.lat,found.lng],18);setMessage(`Localizado: ${found.label}`);};
 const finish=async()=>{if(draft.length<2){setMessage('Adicione pelo menos dois pontos.');return}const s=current.current;let start=s.points.find(p=>Math.abs(p.lat-draft[0].lat)<1e-9&&Math.abs(p.lng-draft[0].lng)<1e-9);if(!start)start={id:uid(),lat:draft[0].lat,lng:draft[0].lng,kind:s.points.length?'junction':'start'};let end=s.points.find(p=>Math.abs(p.lat-draft[draft.length-1].lat)<1e-9&&Math.abs(p.lng-draft[draft.length-1].lng)<1e-9);if(!end)end={id:uid(),lat:draft[draft.length-1].lat,lng:draft[draft.length-1].lng,kind:'end'};const points=[...s.points];if(!points.some(p=>p.id===start!.id))points.push(start);if(!points.some(p=>p.id===end!.id))points.push(end);if(s.segments.some(x=>x.startPointId===start!.id||x.endPointId===start!.id))points.splice(points.findIndex(p=>p.id===start!.id),1,{...start,kind:start.kind==='start'?'start':'junction'});const m=midpoint(draft),addr=m?await reverseGeocode(m.lat,m.lng):{display:'',road:'',neighbourhood:'',city:'',state:'',postcode:''};const seg:SketchSegment={id:uid(),name:nextSegmentName(s.segments),startPointId:start.id,endPointId:end.id,coordinates:draft,lengthMeters:geometryLength(draft),lengthManual:false,address:addr};commit({...s,points,segments:[...s.segments,seg],startPointId:s.startPointId||start.id});setDraft([]);setMode('idle');setBranchPoint(null);setMessage(addr.display?'Endereço do trecho identificado automaticamente.':'Trecho salvo. Endereço pode ser preenchido manualmente.');};
 useEffect(()=>{if(!el.current||map.current)return;const m=L.map(el.current,{zoomControl:true}).setView(center,14);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'© OpenStreetMap contributors',crossOrigin:true}).addTo(m);layer.current=L.layerGroup().addTo(m);map.current=m;setTimeout(()=>m.invalidateSize(),100);return()=>{m.remove();map.current=null}},[]);
 useEffect(()=>{if(el.current)el.current.dataset.mode=mode},[mode]);
 useEffect(()=>{const m=map.current,g=layer.current;if(!m||!g)return;g.clearLayers();const s=value;s.segments.forEach(seg=>{L.polyline(seg.coordinates.map(p=>[p.lat,p.lng] as L.LatLngExpression),{color:'#087faf',weight:6}).addTo(g)});if(mode==='edit')s.segments.forEach(seg=>seg.coordinates.forEach((q,idx)=>{const icon=L.divIcon({className:'sketch-edit-icon',html:'<span></span>',iconSize:[22,22],iconAnchor:[11,11]});const mk=L.marker([q.lat,q.lng],{draggable:true,icon,zIndexOffset:1000}).addTo(g);mk.on('dragend',()=>{const ll=mk.getLatLng(),coords=seg.coordinates.map((v,j)=>j===idx?{lat:ll.lat,lng:ll.lng}:v),points=s.points.map(p=>p.id===(idx===0?seg.startPointId:idx===seg.coordinates.length-1?seg.endPointId:'')?{...p,lat:ll.lat,lng:ll.lng}:p);const segments=s.segments.map(x=>{if(x.id===seg.id)return{...x,coordinates:coords,lengthMeters:x.lengthManual?x.lengthMeters:geometryLength(coords)};if(idx===0||idx===seg.coordinates.length-1){const pid=idx===0?seg.startPointId:seg.endPointId;if(x.startPointId===pid){const c=[{lat:ll.lat,lng:ll.lng},...x.coordinates.slice(1)];return{...x,coordinates:c,lengthMeters:x.lengthManual?x.lengthMeters:geometryLength(c)}}if(x.endPointId===pid){const c=[...x.coordinates.slice(0,-1),{lat:ll.lat,lng:ll.lng}];return{...x,coordinates:c,lengthMeters:x.lengthManual?x.lengthMeters:geometryLength(c)}}}return x});commit({...s,points,segments})})}));s.points.forEach(p=>{const marker=L.circleMarker([p.lat,p.lng],{radius:p.kind==='start'||p.kind==='end'?8:6,color:'#fff',weight:2,fillColor:p.kind==='start'?'#16803b':p.kind==='end'?'#b42318':'#f5a623',fillOpacity:1}).addTo(g);marker.bindTooltip(p.kind==='start'?'Início':p.kind==='end'?'Final':'Bifurcação');marker.on('click',()=>{if(mode==='branch'){setBranchPoint(p);setDraft([{lat:p.lat,lng:p.lng}]);setMode('draw');setMessage('Ramal iniciado. Toque no mapa para continuar o traçado.')}})});if(s.segments.length&&mode==='idle')fitWork()},[value,mode]);
 useEffect(()=>{const m=map.current;if(!m)return;const click=(e:L.LeafletMouseEvent)=>{if(mode!=='draw')return;setDraft(v=>[...v,{lat:e.latlng.lat,lng:e.latlng.lng}])};m.on('click',click);return()=>{m.off('click',click)}},[mode]);
 useEffect(()=>{const m=map.current;if(!m)return;if(draftLayer.current)m.removeLayer(draftLayer.current);draftLayer.current=draft.length?L.polyline(draft.map(p=>[p.lat,p.lng]),{color:'#d97706',weight:5,dashArray:'8 7'}).addTo(m):null;return()=>{if(draftLayer.current&&m.hasLayer(draftLayer.current))m.removeLayer(draftLayer.current)}},[draft]);
 useEffect(()=>{setTimeout(()=>map.current?.invalidateSize(),100)},[]);
 const updateSeg=(id:string,patch:Partial<SketchSegment>)=>commit({...value,segments:value.segments.map(x=>x.id===id?{...x,...patch}:x)});
 const removeSeg=(id:string)=>{const segments=value.segments.filter(x=>x.id!==id),used=new Set(segments.flatMap(x=>[x.startPointId,x.endPointId])),points=value.points.filter(p=>used.has(p.id));commit({...value,segments,points,startPointId:points.some(p=>p.id===value.startPointId)?value.startPointId:(points[0]?.id||null)});};
 return <div className="sketch-editor">
  <form className="sketch-search" onSubmit={e=>{e.preventDefault();void doSearch()}}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pesquisar endereço para localizar no mapa" aria-label="Pesquisar endereço no mapa"/><button type="submit" disabled={searching||!query.trim()}>{searching?'Buscando...':'Buscar'}</button><button type="button" className="secondary" disabled={!value.segments.length} onClick={fitWork}>⌖ Enquadrar obra</button></form>
  <div className="sketch-toolbar"><button type="button" className={mode==='draw'&&!branchPoint?'active-tool':''} onClick={startNew}>+ Novo trecho</button><button type="button" className={`secondary ${mode==='branch'||branchPoint?'active-tool':''}`} disabled={!value.points.length} onClick={startBranch}>Criar ramal</button><button type="button" className={`secondary ${mode==='edit'?'active-tool':''}`} disabled={!value.segments.length} onClick={()=>{setMode(mode==='edit'?'idle':'edit');setMessage(mode==='edit'?'Edição encerrada.':'Arraste as alças azuis para ajustar o traçado.')}}>{mode==='edit'?'Concluir edição':'Editar pontos'}</button>{mode==='draw'&&<button type="button" onClick={()=>void finish()}>Concluir trecho</button>}{mode==='draw'&&<button type="button" className="ghost" onClick={()=>setDraft(v=>v.slice(0,-1))}>Desfazer ponto</button>}<button type="button" className="ghost" disabled={!history.current.length} onClick={undo}>Desfazer alteração</button></div>
  {message&&<p className="hint sketch-message">{message}</p>}
  <div ref={el} className="sketch-map" aria-label="Mapa do croqui da solução proposta" />
  <p className="hint">Mapa: © OpenStreetMap contributors. A pesquisa, o mapa-base e a busca automática de endereço dependem de internet; os trechos já cadastrados permanecem salvos localmente.</p>
  {value.segments.length>0&&<div className="table-scroll sketch-table"><table><thead><tr><th>Trecho</th><th>Endereço</th><th>Extensão</th><th></th></tr></thead><tbody>{value.segments.map(seg=><tr key={seg.id}><td><input value={seg.name} onChange={e=>updateSeg(seg.id,{name:e.target.value})}/></td><td><input value={addressLabel(seg.address)} onChange={e=>updateSeg(seg.id,{address:{...seg.address,display:e.target.value,road:'',neighbourhood:'',city:'',state:'',postcode:''}})}/></td><td><div className="sketch-length"><input type="number" min="0" step="0.1" inputMode="decimal" value={Number(seg.lengthMeters.toFixed(1))} onChange={e=>updateSeg(seg.id,{lengthMeters:Number(e.target.value)||0,lengthManual:true})}/><span>m</span>{seg.lengthManual&&<button type="button" className="ghost compact" title="Recalcular pela geometria" onClick={()=>updateSeg(seg.id,{lengthMeters:geometryLength(seg.coordinates),lengthManual:false})}>↻</button>}</div></td><td><button type="button" className="icon danger" title="Excluir trecho" onClick={()=>removeSeg(seg.id)}>×</button></td></tr>)}</tbody><tfoot><tr><th colSpan={2}>Extensão total</th><th>{formatLength(value.totalLengthMeters)}</th><th></th></tr></tfoot></table></div>}
 </div>;
}
